typedef enum {
    LEXICAL_ERROR = 1,
    SYNTAX_ERROR,
    SEMANTIC_UNDEFINED_VAR_ERROR,
    SEMANTIC_TYPE_DERIVATION_OF_NEW_VAR_ERROR,
    SEMANTIC_DATA_TYPES_ERROR,
    SEMANTIC_FUNCTION_ERROR,
    SEMANTIC_OTHER_ERRORS,
    SEMANTIC_ZERO_DIVIDION_ERROR = 9,
    INTERNAL_ERROR = 99
} Errors_list;